### ISSUE TITLE
Support CompletionItem.additionalTextEdits

### ISSUE THREAD

**Issue by JanKoehnlein** [TypeFox/monaco-languageclient#39]
`CompletionItem#additionalTextEdits` from the langauge server are currently not converted. 

I'd need that for the new Go language server to automatically add a missing import, when a function from a not yet imported package is chosen as a completion.

**Comment by akosyakov** [comment]
Unfortunately, monaco does not support it. We will need to expose some internal VS code APIs to register custom completion item providers.

**Comment by akosyakov** [comment]
PRs are welcomed.

It should be first fixed in vscode: https://github.com/Microsoft/monaco-editor/issues/642#issuecomment-347200856

- Monaco typings should be adjusted
- [conversions](https://github.com/Microsoft/vscode/blob/63efefc7c279e7c963d223123d7248137034252a/src/vs/editor/standalone/browser/standaloneLanguages.ts#L626) should be adjusted as well

After that, it should be fixed in this repo.

**Comment by JanKoehnlein** [comment]
Now that the vscode changes are merged. What is left to do?

**Comment by rcjsuen** [comment]
@JanKoehnlein If I understand correctly, I think the Monaco Editor packages need to be updated and published to npm so that it can be consumed here.

**Comment by akosyakov** [comment]
Should be resolved by https://github.com/TypeFox/monaco-languageclient/pull/63

**Comment by rcjsuen** [comment]
Sorry, I should've been clearer with [what I said](https://github.com/TypeFox/monaco-languageclient/issues/61#issue-305337514). This isn't fixed yet because the code is still commented out. I didn't want to just uncomment the code without verifying it.

https://github.com/TypeFox/monaco-languageclient/blob/1542fc57730755718cde3e0a0b9e257ea96cf933/src/converter.ts#L108-L114
